services:
  db:
    container_name: 'db'
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    command: postgres -p ${DB_PORT}
    ports:
      - '${DB_PORT}:${DB_PORT}'